# Generated by Django 4.1.13 on 2024-02-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('beverages', 'Beverages'), ('snacks', 'Snacks'), ('desserts', 'Desserts'), ('deals', 'Deals')], max_length=9),
        ),
    ]
