# Generated by Django 4.1.13 on 2024-02-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNo', models.IntegerField(max_length=4)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('free', 'Free')], default='free', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tablereservation',
            name='status',
        ),
        migrations.AlterField(
            model_name='menu',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='tableNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.table'),
        ),
    ]
